Add the json files to the Part Factories
Except for Calligra Author, because that has put its
part factory in the same dynamic library as the Words
part factory, which means we've got two entry points
for a plugin in the same so, which doesn't work:

[ 35%] Building CXX object words/part/CMakeFiles/wordsprivate.dir/wordsprivate_automoc.cpp.o
In file included from /home/boud/kde/build/calligra/words/part/wordsprivate_automoc.cpp:15:0:
/home/boud/kde/build/calligra/words/part/moc_CAuFactory.cpp:92:39: error: redefinition of ‘const uint qt_section_alignment_dummy’
In file included from /home/boud/kde/build/calligra/words/part/wordsprivate_automoc.cpp:5:0:
/home/boud/kde/build/calligra/words/part/moc_KWFactory.cpp:92:39: error: ‘const uint qt_section_alignment_dummy’ previously defined here
In file included from /home/boud/kde/build/calligra/words/part/wordsprivate_automoc.cpp:15:0:
/home/boud/kde/build/calligra/words/part/moc_CAuFactory.cpp:236:46: error: redefinition of ‘const unsigned char qt_pluginMetaData []’
In file included from /home/boud/kde/build/calligra/words/part/wordsprivate_automoc.cpp:5:0:
/home/boud/kde/build/calligra/words/part/moc_KWFactory.cpp:249:28: error: ‘const unsigned char qt_pluginMetaData [1168]’ previously defined here
In file included from /home/boud/kde/build/calligra/words/part/wordsprivate_automoc.cpp:15:0:
/home/boud/kde/build/calligra/words/part/moc_CAuFactory.cpp: In function ‘const char* qt_plugin_query_metadata()’:
/home/boud/kde/build/calligra/words/part/moc_CAuFactory.cpp:373:1: error: redefinition of ‘const char* qt_plugin_query_metadata()’
In file included from /home/boud/kde/build/calligra/words/part/wordsprivate_automoc.cpp:5:0:
/home/boud/kde/build/calligra/words/part/moc_KWFactory.cpp:399:1: error: ‘const char* qt_plugin_query_metadata()’ previously defined here
In file included from /home/boud/kde/build/calligra/words/part/wordsprivate_automoc.cpp:15:0:
/home/boud/kde/build/calligra/words/part/moc_CAuFactory.cpp: In function ‘QObject* qt_plugin_instance()’:
/home/boud/kde/build/calligra/words/part/moc_CAuFactory.cpp:373:1: error: redefinition of ‘QObject* qt_plugin_instance()’
In file included from /home/boud/kde/build/calligra/words/part/wordsprivate_automoc.cpp:5:0:
/home/boud/kde/build/calligra/words/part/moc_KWFactory.cpp:399:1: error: ‘QObject* qt_plugin_instance()’ previously defined here
make[2]: *** [words/part/CMakeFiles/wordsprivate.dir/wordsprivate_automoc.cpp.o] Error 1
make[1]: *** [words/part/CMakeFiles/wordsprivate.dir/all] Error 2