o compile++ put back KIS_SHAPE_LAYER_ID as it is still used here:
./plugins/tools/tool_transform/kis_tool_transform.cc:804:    } else if ( shape->shapeId() == KIS_SHAPE_LAYER_ID ) {
./ui/kis_tool.cc:231:    } else if ( shape->shapeId() == KIS_SHAPE_LAYER_ID ) {
./ui/kis_shape_controller.cpp:138:         || shape->shapeId() == KIS_SHAPE_LAYER_ID
./ui/kis_shape_controller.cpp:160:         shape->shapeId() != KIS_SHAPE_LAYER_ID  &&
./ui/kis_shape_layer.cc:64:    setShapeId( KIS_SHAPE_LAYER_ID );

however krita does still not compile:
  [ 54%] Building CXX object
  krita/image/tests/CMakeFiles/KisCountVisitorTest.dir/kis_count_visitor_test.o
  /home/tz/develop/kde/svn/koffice/krita/image/tests/kis_count_visitor_test.cpp:
  In member function 'void KisCountVisitorTest::testCounting()':
  /home/tz/develop/kde/svn/koffice/krita/image/tests/kis_count_visitor_test.cpp:44:
  error: cannot allocate an object of abstract type 'KisNode'
  /home/tz/develop/kde/svn/koffice/krita/image/kis_node.h:36: note:
  because the following virtual functions are pure within 'KisNode':
  /home/tz/develop/kde/svn/koffice/krita/image/kis_node.h:61: note:
  virtual KisNodeSP KisNode::clone()
  /home/tz/develop/kde/svn/koffice/krita/image/kis_node.h:74: note:
  virtual bool KisNode::allowAsChild(KisNodeSP)



svn path=/trunk/koffice/; revision=722289