Fix build with QT 4.8.
KDChartBackgroundAttributes.cpp:153:26: error: ambiguous overload for 'operator<<' in '((QDebug*)((QDebug*)operator<<(QDebug, const QBrush&)(((const QBrush&)((const QBrush*)(& KDChart::BackgroundAttributes::brush() const())))).QDebug::operator<<(((const char*)"pixmapmode=")))->QDebug::operator<<(((int)((const KDChart::BackgroundAttributes*)ba)->KDChart::BackgroundAttributes::pixmapMode())))->QDebug::operator<<(((const char*)"pixmap=")) << KDChart::BackgroundAttributes::pixmap() const()'

It does not know if it should convert QPixmap to QVariant or QBrush before dumping it into
qDebug(). It happens because with qt4.8 qvariant is included implictely with klocale.h over
qlocale.h. Which was not the case before qt4.8.

Related:     QTBUG-19764: Please add QDebug operator for QPixmap