Make build:
/usr/include/QtCore/qmap.h: In instantiation of ‘QMapData<Key, T>::Node* QMapData<Key, T>::createNode(const Key&, const T&, QMapData<Key, T>::Node*, bool) [with Key = QString; T = KisMetaData::Validator::Reason; QMapData<Key, T>::Node = QMapNode<QString, KisMetaData::Validator::Reason>]’:
/usr/include/QtCore/qmap.h:663:50:   required from ‘QMap<Key, T>::iterator QMap<Key, T>::insert(const Key&, const T&) [with Key = QString; T = KisMetaData::Validator::Reason]’
/usr/include/QtCore/qmap.h:613:33:   required from ‘T& QMap<Key, T>::operator[](const Key&) [with Key = QString; T = KisMetaData::Validator::Reason]’
/home/boud/kde/src/calligra/krita/image/metadata/kis_meta_data_validator.cc:93:60:   required from here
/home/boud/kde/src/calligra/krita/image/metadata/kis_meta_data_validator.cc:40:1: error: ‘KisMetaData::Validator::Reason::Reason(const KisMetaData::Validator::Reason&)’ is private
In file included from /usr/include/QtCore/QMap:1:0,
                 from /home/boud/kde/src/calligra/krita/image/metadata/kis_meta_data_validator.h:22,
                 from /home/boud/kde/src/calligra/krita/image/metadata/kis_meta_data_validator.cc:19:
/usr/include/QtCore/qmap.h:218:17: error: within this context
make[2]: *** [krita/image/CMakeFiles/kritaimage.dir/metadata/kis_meta_data_validator.cc.o] Error 1
make[1]: *** [krita/image/CMakeFiles/kritaimage.dir/all] Error 2
make: *** [all] Error 2