flake: Include <cmath> rather than <math.h>
With the latter I get an build error with gcc-5:
"KoSnapStrategy.cpp:78:14: error: '__builtin_isfinite' is not a
member of 'std'".

Also remove no longer needed #define because plain isfinite isn't
used anymore.

Test Plan: Builds fine

Reviewers: Calligra-Devel-list, kossebau

Reviewed By: kossebau

Subscribers: kossebau

Tags: #kexi, #calligra:_3.0

Differential Revision: https://phabricator.kde.org/D2702